version: '3'
services: 
  nginx: 
    image: nginx
    ports:
      - "3600:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app

  node-app:
    build: .
    environment:
      - PORT=3600
    depends_on:
      - mongo
      - redis

  mongo: 
    image: mongo:4.4.6
    environment: 
        - MONGO_INITDB_ROOT_USERNAME=metasix
        - MONGO_INITDB_ROOT_PASSWORD=Horlarmideh
    volumes: 
      - mongo-db:/data/db

  redis: 
    image: redis
    ports:
      - 6379:6379
    
volumes:
  mongo-db: