version: '3'
services: 
  nginx: 
    ports:
      - "3600:80"
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes: 
      - ./:/app
      - /app/node_modules
    environment: 
      - NODE_ENV= development
      - MONGO_USER=metasix
      - MONGO_PASS=Horlarmideh
      - SESSION_SECRET=secret
    command: npm run dev

  mongo: 
    image: mongo:4.4.6
    environment: 
        - MONGO_INITDB_ROOT_USERNAME=metasix
        - MONGO_INITDB_ROOT_PASSWORD=Horlarmideh
  